ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'NEGOTIATION_MANAGER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'NEGOTIATION_RESOURCE';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'FLEET_MANAGER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'DRIVER';
