DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'SiteType') THEN
        CREATE TYPE "SiteType" AS ENUM ('WORKSITE', 'WAREHOUSE', 'MATERIAL_PICKUP', 'OFFICE', 'CLIENT_SITE', 'OTHER');
    END IF;
END $$;

ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "siteType" "SiteType" NOT NULL DEFAULT 'WORKSITE';
ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "requiresClockIn" BOOLEAN NOT NULL DEFAULT true;

